import { TierDefinition } from '@/types';

export const TIERS: Record<string, TierDefinition> = {
  free: {
    id: 'free',
    name: 'Free',
    price_monthly_usd: 0,
    price_annual_usd: 0,
    price_monthly_npr: 0,
    price_annual_npr: 0,
    description: 'Perfect to get started',
    color: 'gray',
    features: [
      { name: 'Up to 5 listings', included: true },
      { name: 'Basic analytics', included: true },
      { name: 'Email support', included: true },
      { name: 'Verified badge', included: false },
      { name: 'Priority support', included: false },
      { name: 'Advanced analytics', included: false },
    ],
  },
  small: {
    id: 'small',
    name: 'Small',
    price_monthly_usd: 29,
    price_annual_usd: 290,
    price_monthly_npr: 3800,
    price_annual_npr: 38000,
    description: 'For growing agencies',
    color: 'blue',
    features: [
      { name: 'Up to 20 listings', included: true },
      { name: 'Basic analytics', included: true },
      { name: 'Email support', included: true },
      { name: 'Verified badge', included: true },
      { name: 'Priority support', included: false },
      { name: 'Advanced analytics', included: false },
    ],
  },
  medium: {
    id: 'medium',
    name: 'Medium',
    price_monthly_usd: 79,
    price_annual_usd: 790,
    price_monthly_npr: 10400,
    price_annual_npr: 104000,
    description: 'For established agencies',
    color: 'purple',
    features: [
      { name: 'Unlimited listings', included: true },
      { name: 'Basic analytics', included: true },
      { name: 'Email support', included: true },
      { name: 'Verified badge', included: true },
      { name: 'Priority support', included: true },
      { name: 'Advanced analytics', included: false },
    ],
  },
  large: {
    id: 'large',
    name: 'Large',
    price_monthly_usd: 199,
    price_annual_usd: 1990,
    price_monthly_npr: 26200,
    price_annual_npr: 262000,
    description: 'For premium agencies',
    color: 'green',
    features: [
      { name: 'Unlimited listings', included: true },
      { name: 'Basic analytics', included: true },
      { name: 'Email support', included: true },
      { name: 'Verified badge', included: true },
      { name: 'Priority support', included: true },
      { name: 'Advanced analytics', included: true },
    ],
  },
};
